[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0"
axum = "0.7"
dotenv = "0.15"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
] }
