services:
  mongodb:
    image: mongo:7
    container_name: be-mongodb
    ports:
      - "27017:27017"
    volumes:
      - be-mongodb:/data/db

  pgdb:
    image: postgres:16
    container_name: be-pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - be-pgdb:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: be-redis
    ports:
      - "6379:6379"

volumes:
  be-pgdb:
  be-mongodb:
